export const freeModels = [
  {
    id: "gemini-2.5-flash-preview-04-17",
    name: "Gemini 2.5 Flash Preview 04-17",
    description: "Adaptive thinking, cost efficiency",
    inputs: "Audio, images, videos, and text",
    output: "Text",
    optimizedFor: "Adaptive thinking, cost efficiency",
    inputTokenLimit: "1,048,576",
    outputTokenLimit: "65,536",
    keyCapabilities: "Code execution, function calling, search grounding, structured outputs, thinking",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    description: "Next generation features, speed, thinking, realtime streaming, and multimodal generation",
    inputs: "Audio, images, videos, and text",
    output: "Text, images (experimental), audio (coming soon)",
    optimizedFor: "Next generation features, speed, thinking, realtime streaming, and multimodal generation",
    inputTokenLimit: "1,048,576",
    outputTokenLimit: "8,192",
    keyCapabilities: "Structured outputs, caching, function calling, code execution, search, Live API, thinking (experimental)",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    description: "Cost efficiency and low latency",
    inputs: "Audio, images, videos, and text",
    output: "Text",
    optimizedFor: "Cost efficiency and low latency",
    inputTokenLimit: "1,048,576",
    outputTokenLimit: "8,192",
    keyCapabilities: "Structured outputs, caching, function calling",
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    description: "Fast and versatile performance across a diverse variety of tasks",
    inputs: "Audio, images, videos, and text",
    output: "Text",
    optimizedFor: "Fast and versatile performance across a diverse variety of tasks",
    inputTokenLimit: "1,048,576",
    outputTokenLimit: "8,192",
    keyCapabilities: "System instructions, JSON mode, JSON schema, adjustable safety settings, caching, tuning, function calling, code execution",
  },
  {
    id: "gemini-1.5-flash-8b",
    name: "Gemini 1.5 Flash-8B",
    description: "High volume and lower intelligence tasks",
    inputs: "Audio, images, videos, and text",
    output: "Text",
    optimizedFor: "High volume and lower intelligence tasks",
    inputTokenLimit: "1,048,576",
    outputTokenLimit: "8,192",
    keyCapabilities: "System instructions, JSON mode, JSON schema, adjustable safety settings, caching, tuning, function calling, code execution",
  },
];
