import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins

// Configure the Poppins font
const poppins = Poppins({
  weight: ["400", "700"], // Specify the weights you want to use
  subsets: ["latin"], // Specify the subsets you need
  display: "swap", // Recommended setting for font display
  variable: "--font-poppins", // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Poppins font variable to the body */}
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
